### ISSUE TITLE
Windows installation - Documentation Suggestions

### ISSUE THREAD

**Issue by mriedmann** [SandoghdarLab/PiSCAT#2]
Hi!

I installed this (piscat==0.1.12) on Windows 10 using python 3.9 (windows store edition) and I have to say it was a bit challenging. The following points could help other people to get this project to work.

- Using a virtualenv is highly recommended and saves a lot of pain. I should have done this from the beginning. Also, using the "windows store" edition of Python is way more convenient the using the "official" installer, but that might be personal preference.
  - to create a virtualenv simply run `python -m venv .venv` using the commandline (cmd.exe) in an empty folder (`mkdir somefolder` `cd somefolder`). After that activate the env executing `activate.bat` in the `.venv/Scripts` folder.
  - in the activated environment run `pip install piscat`
- The installation crashed because H5PY 2.10.0 was not available as normal wheel using pip, I had to download the modified version from this site: https://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py. After that I installed it using `pip install <filename>`. There might me a better way but this worked quite well.
- After installation I had to downgrade some dependencies because of mysterious DLL loading problems. I was able to start the GUI using the following versions:
  - `Pillow==8.2.0`
  - `matplotlib==3.3.1`
  - `scikit-image==0.18.0rc0`
  - I also installed `msvc-runtime` but I am not sure if that solved anything

And another small thing: The data download-step in Tutorial1 failed with an SSL verification error. I downloaded the files from the URLs provided inside the code, extracted the files manually and added them to the data-folder. After that the Tutorial worked without any troubles. There was no problem on my linux machine and also Chrome did not show any errors. I would assume that the SSL library on windows uses a reduced set of trusted CAs, but that's only a guess.

It might also be a good idea to host the tutorial-files as artifacts to your releases on Github instead. It would be a shame to lose this data and break the tutorial functionality if someone migrates/updates/deletes the used owncloud instance.

Hope this helps whoever might need it :)

Cheers, Michael

**Comment by po60nani** [comment]
Thank you for your comments. Installing PiSCAT==0.1.12 with Python 3.8 is highly recommended. We're working on a new version that uses Python 3.9, a new version of H5PY, and QT6 to solve the majority of the issues.
