### ISSUE TITLE
Tutorial 5, iSCAT, material of particle

### ISSUE THREAD

**Issue by morti3091** [SandoghdarLab/PiSCAT#9]
Hey,

I am using your model to simulate iPSF functions. I did the tutorial 5 and everything worked fine.
However, I would like to change the material parameters i.e. instead of a gold particle use e.g. a silver particle but I can not find how to incorporate these parameters.
Is there a way to account for size and material of the particle?

Best,
Phil

**Comment by po60nani** [comment]
Hi, Please contact with my colleague @Reza-GhM "reza.gholami@mpl.mpg.de"

**Comment by morti3091** [comment]
Thanks for the contact, I will do so :)
